### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [OS-IS/ai201-mojseev#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
10) Відомо, що GitHub-сервер використовує Token для процедури аутентифікації користувача. 
Але під час створення Token система запропонували вам виконати додаткові налаштування. 
Поясніть, будь ласка, які налаштування та з якому метою було вами виконано?

**Comment by moiseiev** [comment]
Я зробив такі налаштування під час створення токену:

    Вибрав обсяг доступу repo: Щоб мій токен мав доступ до приватного репозиторію, оскільки це потрібно для інтеграції з інструментом автоматизації, який використовує код із цього репозиторію.

    Не надавав права delete_repo та admin:org: Я обмежив ці права, оскільки вони не потрібні для виконання моїх завдань, і це підвищує безпеку використання токену.

    Встановив термін дії на 30 днів: Таким чином, навіть якщо токен буде скомпрометовано, його дія автоматично завершиться, що зменшує ризики несанкціонованого доступу.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
Дякую.
